- title: Data Manipulation and Visualisation
  subtitle: In this course, we give an introduction to the R environment and explain how it can be used to import, manipulate and visualise tabular data.
  description: After the course you should feel confident to start exploring your own dataset using the materials and references provided.
  date: 17-09-2019
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: SITraN
  link: http://sbc.shef.ac.uk/training/r-introduction-2019-09-17/

- title: Nanopore Sequencing & Data Analysis
  subtitle: Learn about nanopore sequecning and data analysis by performing your own 16S sequecning experiement!
  description: Learn - The science behind nanopore sequencing, How to prepare a 16S amplicon library for sequencing, Loading a library onto a MinION flow cell, Sequencing on the MinION platform, Basics of nanopore data, Analysis of our 16S data using Galaxy
  date: 19-09-2019
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: E13 Dainton Building
  link: http://sbc.shef.ac.uk/training/nanopore-sequencing-2019-09-19/

- title: Statistical Analysis of Biological Data in R
  subtitle: Using R for the analysis of biological data
  description: This course provides a refresher on the foundations of statistical analysis. The course is aimed at scientists at all levels – especially those whose formal education likely included statistics, but who have not perhaps put this into practice since. The focus of the course is on understanding the principles behind statistical testing, how to choose and execute the most appropriate test for your data, and how to interpret the result.
  date: 18-09-2019
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: SITraN
  link: http://sbc.shef.ac.uk/training/stats-introduction-2019-09-18/

- title: Introduction to Practical Bioinformatics
  subtitle: This intensive two-day course aims to introduce scientists to the command-line interface and the R programming environment.
  description: Day 1 begins with an introduction to the Linux command-line, covering essential core utilities before moving on to introduce command-line BLAST and shell scripting. Day 2 further develops shell scripting skills, then moves on to introduce data handling in the R statistical programming environment. We start from the basics without assuming any prior knowledge.
  date: 17-09-2019
  duration: 2
  institute: Newcastle University
  city: Newcastle
  location: Newcastle University Campus
  link: https://www.ncl.ac.uk/bsu/courses/

- title: RNA-Seq Data Analysis
  subtitle: This one-day course covers important aspects of Bioinformatics and the analysis of high-throughput sequencing data.
  description: We work though an RNA-Seq Analysis example using Salmon for quantification, and the popular DESeq2 package for differential gene expression analysis.
  date: 19-09-2019
  duration: 1
  institute: Newcastle University
  city: Newcastle
  location: Newcastle University Campus
  link: https://www.ncl.ac.uk/bsu/courses/

- title: Interpreting RNA-Seq Results
  subtitle: This one-day course looks at several ways of adding functional context to lists of genes.
  description: We begin by introducing methods for clustering and visualizing data, including dendrograms, heatmaps and venn diagrams. We then consider how to make use of functional annotation that has been added to the gene databases of many organisms to examine gene lists for classes of annotation that are statistically over-represented.
  date: 20-09-2019
  duration: 1
  institute: Newcastle University
  city: Newcastle
  location: Newcastle University Campus
  link: https://www.ncl.ac.uk/bsu/courses/

- title: Introduction to RNA-seq in R
  subtitle: In this workshop, you will be learning how to analyse RNA-seq count data, using R. 
  description: You will learn how to generate common plots for analysis and visualisation of gene expression data, such as boxplots and heatmaps. You will also be learning how alignment and counting of raw RNA-seq data can be performed in R. This workshop is aimed at biologists interested in learning how to perform differential expression analysis of RNA-seq data when reference genomes are available
  date: 13-11-2019
  duration: 2
  institute: University of Sheffield
  location: Pam Liversidge Building, Design Studio 1, D06
  link: http://sbc.shef.ac.uk/training/rna-seq-in-r-2019-11-13/
  

- title: Next Generation Biologists’ Genomics Workshop
  subtitle: Introduction to command-line analysis of next-generation sequencing data (QC, mapping, variant calling and cloud computing)
  description: Next Generation Biologists: Essential Computing Skills for Molecular Biology is a BBSRC-STARs programme-funded project to introduce and train researchers in the skills and best practices in scientific computing and bioinformatics. Programme will be based on (but not identical to) the new Carpentries’ Genomics curriculum and will include manipulation of FASTQ files, alignment to reference genome, variant calling and introduction to cloud computing.
  date: 16-12-2019
  duration: 2
  institute: University of Leeds
  city: Leeds
  location: TBA
  link: http://nextgenbiologists.org
  
- title: Nanopore Sequencing & Data Analysis
  subtitle: Learn about nanopore sequecning and data analysis by performing your own 16S sequecning experiement!
  description: Learn - The science behind nanopore sequencing, How to prepare a 16S amplicon library for sequencing, Loading a library onto a MinION flow cell, Sequencing on the MinION platform, Basics of nanopore data, Analysis of our 16S data using Galaxy
  date: 03-12-2019
  duration: 2
  institute: University of Sheffield
  city: Sheffield
  location: E13 Dainton Building
  link: http://sbc.shef.ac.uk/training/nanopore-sequencing-2019-12-03/
  
- title: RNA-seq for Beginners
  subtitle: Overview of the analysis pipeline for RNA-seq
  description: We will describe the steps involved to go from sequencing library to a list of genes that show statistically significant differences between your biological conditions of interest. Practical sessions will use the user-friendly Galaxy interface (https://usegalaxy.org/) to demonstrate tasks such as alignment, quality control and assessing differential expression
  date: 09-12-2019
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: Pam Liversidge Design Studio 1 - D06
  link: http://sbc.shef.ac.uk/training/rna-seq-introduction-2019-12-09/

- title: Data Manipulation and Visualisation
  subtitle: In this course, we give an introduction to the R environment and explain how it can be used to import, manipulate and visualise tabular data.
  description: After the course you should feel confident to start exploring your own dataset using the materials and references provided.
  date: 03-03-2020
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: Pam Liversidge Design Studio 1 - D06
  link: http://sbc.shef.ac.uk/training/r-introduction-2020-03-03/
  
- title: Statistical Analysis of Biological Data in R
  subtitle: Using R for the analysis of biological data
  description: This course provides a refresher on the foundations of statistical analysis. The course is aimed at scientists at all levels – especially those whose formal education likely included statistics, but who have not perhaps put this into practice since. The focus of the course is on understanding the principles behind statistical testing, how to choose and execute the most appropriate test for your data, and how to interpret the result.
  date: 05-03-2020
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: Pam Liversidge Design Studio 1 - D06
  link: http://sbc.shef.ac.uk/training/stats-introduction-2020-03-05/
